"""Added phone number column to users

Revision ID: 3fec06350c31
Revises: a672fdca4bf4
Create Date: 2024-11-11 18:39:54.237478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fec06350c31'
down_revision: Union[str, None] = 'a672fdca4bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
