name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'app/**'  # Trigger only when changes occur in the app directory
      - 'docs/**'  # Trigger when docs themselves are changed
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
    paths:
      - 'app/**'  # Trigger only when changes occur in the app directory
      - 'docs/**'  # Trigger when docs themselves are changed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
          pip install sphinx ghp-import  # Install Sphinx and ghp-import

      - name: Build Sphinx documentation
        run: |
          cd docs  # Navigate to the docs folder
          sphinx-build -b html . _build/html  # Build the docs

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f docs/_build/html
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
